Diät für Plug and Play
EVNotify/EVNotiPi pull request #12
Opened 2019-03-12 19:59 UTC by noradtux

2019-03-13 08:49 UTC, GPlay97 commented on evnotipi.py
> +            print(e)
was ist mit dem Delay poll?

2019-03-13 08:49 UTC, GPlay97 commented on evnotipi.py
>  gps = GpsPoller()
gps sollte doch optional nur sein

2019-03-13 08:49 UTC, GPlay97 commented on evnotipi.py
> +CHARGE_COOLDOWN_DELAY = None # 6 h  set to None to disable auto shutdown
müsste aus Config kommen

2019-03-13 08:51 UTC, GPlay97 commented on README.md
> +crontab:
die Readme müsste noch das alte auch alles beinhalten

2019-03-13 08:51 UTC, GPlay97 requested changes
Die offenen Punkte müssten geklärt werden

2019-03-13 20:00 UTC, noradtux commented on evnotipi.py
> +            print(e)
Brauchen wir nicht. Das System fährt komplett runter wenn das relevant werden würde.

2019-03-13 20:01 UTC, noradtux commented on evnotipi.py
>  gps = GpsPoller()
Ja, der Code läuft im Zweifel einfach mit. Sobald man den GPSd mit Daten füttert werden die dann automatisch verabeitet,

2019-03-13 20:06 UTC, noradtux commented on evnotipi.py
> +CHARGE_COOLDOWN_DELAY = None # 6 h  set to None to disable auto shutdown
Den delay vom loop sollten wir hart im Code lassen. Auto Shutdown läuft über den Wemos, hab vergessen die Variable zu löschen.

2019-03-13 20:12 UTC, noradtux commented on README.md
> +crontab:
Siehe neuer Commit

2019-03-14 15:13 UTC, GPlay97 approved these changes

2019-03-14 15:14 UTC, merged