Better handling for bad data
EVNotify/EVNotiPi pull request #20
Opened 2019-04-15 20:09 UTC by noradtux

2019-04-16 11:47 UTC, GPlay97 requested changes

2019-04-16 11:47 UTC, GPlay97 commented on dongles/PiOBD2Hat.py
> +                if value == b'\x00\x00\x00\x00\x00\x00\x00':
I think it's better to not globally handle this inside the obd hat module.
I think it's better to leave this special handling inside the car modules because in theory it could be possible that some blocks are filled with zeroes - we don't know.

2019-04-16 16:02 UTC, noradtux commented on dongles/PiOBD2Hat.py
> +                if value == b'\x00\x00\x00\x00\x00\x00\x00':
Change reverted. Check moved to Ioniq-module

2019-04-17 07:57 UTC, GPlay97 approved these changes

2019-04-17 07:57 UTC, merged